<?php
/**
 * QuoteDataProductOptionExtensionInterface
 *
 * PHP version 5
 *
 * @category Class
 * @package  MagentoApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Community
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace MagentoApi\Model;

use \ArrayAccess;
use \MagentoApi\ObjectSerializer;

/**
 * QuoteDataProductOptionExtensionInterface Class Doc Comment
 *
 * @category Class
 * @description ExtensionInterface class for @see \\Magento\\Quote\\Api\\Data\\ProductOptionInterface
 * @package  MagentoApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QuoteDataProductOptionExtensionInterface implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'quote-data-product-option-extension-interface';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'custom_options' => '\MagentoApi\Model\CatalogDataCustomOptionInterface[]',
'configurable_item_options' => '\MagentoApi\Model\ConfigurableProductDataConfigurableItemOptionValueInterface[]',
'downloadable_option' => '\MagentoApi\Model\DownloadableDataDownloadableOptionInterface',
'bundle_options' => '\MagentoApi\Model\BundleDataBundleOptionInterface[]'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'custom_options' => null,
'configurable_item_options' => null,
'downloadable_option' => null,
'bundle_options' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'custom_options' => 'custom_options',
'configurable_item_options' => 'configurable_item_options',
'downloadable_option' => 'downloadable_option',
'bundle_options' => 'bundle_options'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'custom_options' => 'setCustomOptions',
'configurable_item_options' => 'setConfigurableItemOptions',
'downloadable_option' => 'setDownloadableOption',
'bundle_options' => 'setBundleOptions'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'custom_options' => 'getCustomOptions',
'configurable_item_options' => 'getConfigurableItemOptions',
'downloadable_option' => 'getDownloadableOption',
'bundle_options' => 'getBundleOptions'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['custom_options'] = isset($data['custom_options']) ? $data['custom_options'] : null;
        $this->container['configurable_item_options'] = isset($data['configurable_item_options']) ? $data['configurable_item_options'] : null;
        $this->container['downloadable_option'] = isset($data['downloadable_option']) ? $data['downloadable_option'] : null;
        $this->container['bundle_options'] = isset($data['bundle_options']) ? $data['bundle_options'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets custom_options
     *
     * @return \MagentoApi\Model\CatalogDataCustomOptionInterface[]
     */
    public function getCustomOptions()
    {
        return $this->container['custom_options'];
    }

    /**
     * Sets custom_options
     *
     * @param \MagentoApi\Model\CatalogDataCustomOptionInterface[] $custom_options custom_options
     *
     * @return $this
     */
    public function setCustomOptions($custom_options)
    {
        $this->container['custom_options'] = $custom_options;

        return $this;
    }

    /**
     * Gets configurable_item_options
     *
     * @return \MagentoApi\Model\ConfigurableProductDataConfigurableItemOptionValueInterface[]
     */
    public function getConfigurableItemOptions()
    {
        return $this->container['configurable_item_options'];
    }

    /**
     * Sets configurable_item_options
     *
     * @param \MagentoApi\Model\ConfigurableProductDataConfigurableItemOptionValueInterface[] $configurable_item_options configurable_item_options
     *
     * @return $this
     */
    public function setConfigurableItemOptions($configurable_item_options)
    {
        $this->container['configurable_item_options'] = $configurable_item_options;

        return $this;
    }

    /**
     * Gets downloadable_option
     *
     * @return \MagentoApi\Model\DownloadableDataDownloadableOptionInterface
     */
    public function getDownloadableOption()
    {
        return $this->container['downloadable_option'];
    }

    /**
     * Sets downloadable_option
     *
     * @param \MagentoApi\Model\DownloadableDataDownloadableOptionInterface $downloadable_option downloadable_option
     *
     * @return $this
     */
    public function setDownloadableOption($downloadable_option)
    {
        $this->container['downloadable_option'] = $downloadable_option;

        return $this;
    }

    /**
     * Gets bundle_options
     *
     * @return \MagentoApi\Model\BundleDataBundleOptionInterface[]
     */
    public function getBundleOptions()
    {
        return $this->container['bundle_options'];
    }

    /**
     * Sets bundle_options
     *
     * @param \MagentoApi\Model\BundleDataBundleOptionInterface[] $bundle_options bundle_options
     *
     * @return $this
     */
    public function setBundleOptions($bundle_options)
    {
        $this->container['bundle_options'] = $bundle_options;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
