<?php
/**
 * AmazonPaymentDataQuoteLinkInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MagentoApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Community
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace MagentoApi;

/**
 * AmazonPaymentDataQuoteLinkInterfaceTest Class Doc Comment
 *
 * @category    Class
 * @description AmazonPaymentDataQuoteLinkInterface
 * @package     MagentoApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AmazonPaymentDataQuoteLinkInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AmazonPaymentDataQuoteLinkInterface"
     */
    public function testAmazonPaymentDataQuoteLinkInterface()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "amazon_order_reference_id"
     */
    public function testPropertyAmazonOrderReferenceId()
    {
    }

    /**
     * Test attribute "quote_id"
     */
    public function testPropertyQuoteId()
    {
    }

    /**
     * Test attribute "sandbox_simulation_reference"
     */
    public function testPropertySandboxSimulationReference()
    {
    }

    /**
     * Test attribute "confirmed"
     */
    public function testPropertyConfirmed()
    {
    }
}
