<?php
/**
 * CatalogDataProductRenderFormattedPriceInfoInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MagentoApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Community
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace MagentoApi;

/**
 * CatalogDataProductRenderFormattedPriceInfoInterfaceTest Class Doc Comment
 *
 * @category    Class
 * @description Formatted Price interface. Aggregate formatted html with price representations. E.g.: &lt;span class&#x3D;\&quot;price\&quot;&gt;$9.00&lt;/span&gt; Consider currency, rounding and html
 * @package     MagentoApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CatalogDataProductRenderFormattedPriceInfoInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CatalogDataProductRenderFormattedPriceInfoInterface"
     */
    public function testCatalogDataProductRenderFormattedPriceInfoInterface()
    {
    }

    /**
     * Test attribute "final_price"
     */
    public function testPropertyFinalPrice()
    {
    }

    /**
     * Test attribute "max_price"
     */
    public function testPropertyMaxPrice()
    {
    }

    /**
     * Test attribute "minimal_price"
     */
    public function testPropertyMinimalPrice()
    {
    }

    /**
     * Test attribute "max_regular_price"
     */
    public function testPropertyMaxRegularPrice()
    {
    }

    /**
     * Test attribute "minimal_regular_price"
     */
    public function testPropertyMinimalRegularPrice()
    {
    }

    /**
     * Test attribute "special_price"
     */
    public function testPropertySpecialPrice()
    {
    }

    /**
     * Test attribute "regular_price"
     */
    public function testPropertyRegularPrice()
    {
    }

    /**
     * Test attribute "extension_attributes"
     */
    public function testPropertyExtensionAttributes()
    {
    }
}
