<?php
/**
 * DirectoryDataCountryInformationInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MagentoApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Community
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace MagentoApi;

/**
 * DirectoryDataCountryInformationInterfaceTest Class Doc Comment
 *
 * @category    Class
 * @description Country Information interface.
 * @package     MagentoApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DirectoryDataCountryInformationInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DirectoryDataCountryInformationInterface"
     */
    public function testDirectoryDataCountryInformationInterface()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "two_letter_abbreviation"
     */
    public function testPropertyTwoLetterAbbreviation()
    {
    }

    /**
     * Test attribute "three_letter_abbreviation"
     */
    public function testPropertyThreeLetterAbbreviation()
    {
    }

    /**
     * Test attribute "full_name_locale"
     */
    public function testPropertyFullNameLocale()
    {
    }

    /**
     * Test attribute "full_name_english"
     */
    public function testPropertyFullNameEnglish()
    {
    }

    /**
     * Test attribute "available_regions"
     */
    public function testPropertyAvailableRegions()
    {
    }

    /**
     * Test attribute "extension_attributes"
     */
    public function testPropertyExtensionAttributes()
    {
    }
}
