<?php
/**
 * DirectoryDataCurrencyInformationInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MagentoApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Community
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace MagentoApi;

/**
 * DirectoryDataCurrencyInformationInterfaceTest Class Doc Comment
 *
 * @category    Class
 * @description Currency Information interface.
 * @package     MagentoApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DirectoryDataCurrencyInformationInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DirectoryDataCurrencyInformationInterface"
     */
    public function testDirectoryDataCurrencyInformationInterface()
    {
    }

    /**
     * Test attribute "base_currency_code"
     */
    public function testPropertyBaseCurrencyCode()
    {
    }

    /**
     * Test attribute "base_currency_symbol"
     */
    public function testPropertyBaseCurrencySymbol()
    {
    }

    /**
     * Test attribute "default_display_currency_code"
     */
    public function testPropertyDefaultDisplayCurrencyCode()
    {
    }

    /**
     * Test attribute "default_display_currency_symbol"
     */
    public function testPropertyDefaultDisplayCurrencySymbol()
    {
    }

    /**
     * Test attribute "available_currency_codes"
     */
    public function testPropertyAvailableCurrencyCodes()
    {
    }

    /**
     * Test attribute "exchange_rates"
     */
    public function testPropertyExchangeRates()
    {
    }

    /**
     * Test attribute "extension_attributes"
     */
    public function testPropertyExtensionAttributes()
    {
    }
}
