<?php
/**
 * MsrpDataProductRenderMsrpPriceInfoInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MagentoApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Community
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace MagentoApi;

/**
 * MsrpDataProductRenderMsrpPriceInfoInterfaceTest Class Doc Comment
 *
 * @category    Class
 * @description Price interface.
 * @package     MagentoApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MsrpDataProductRenderMsrpPriceInfoInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MsrpDataProductRenderMsrpPriceInfoInterface"
     */
    public function testMsrpDataProductRenderMsrpPriceInfoInterface()
    {
    }

    /**
     * Test attribute "msrp_price"
     */
    public function testPropertyMsrpPrice()
    {
    }

    /**
     * Test attribute "is_applicable"
     */
    public function testPropertyIsApplicable()
    {
    }

    /**
     * Test attribute "is_shown_price_on_gesture"
     */
    public function testPropertyIsShownPriceOnGesture()
    {
    }

    /**
     * Test attribute "msrp_message"
     */
    public function testPropertyMsrpMessage()
    {
    }

    /**
     * Test attribute "explanation_message"
     */
    public function testPropertyExplanationMessage()
    {
    }

    /**
     * Test attribute "extension_attributes"
     */
    public function testPropertyExtensionAttributes()
    {
    }
}
