<?php
/**
 * QuoteDataCurrencyInterfaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  MagentoApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Magento Community
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.16
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace MagentoApi;

/**
 * QuoteDataCurrencyInterfaceTest Class Doc Comment
 *
 * @category    Class
 * @description Interface CurrencyInterface
 * @package     MagentoApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QuoteDataCurrencyInterfaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QuoteDataCurrencyInterface"
     */
    public function testQuoteDataCurrencyInterface()
    {
    }

    /**
     * Test attribute "global_currency_code"
     */
    public function testPropertyGlobalCurrencyCode()
    {
    }

    /**
     * Test attribute "base_currency_code"
     */
    public function testPropertyBaseCurrencyCode()
    {
    }

    /**
     * Test attribute "store_currency_code"
     */
    public function testPropertyStoreCurrencyCode()
    {
    }

    /**
     * Test attribute "quote_currency_code"
     */
    public function testPropertyQuoteCurrencyCode()
    {
    }

    /**
     * Test attribute "store_to_base_rate"
     */
    public function testPropertyStoreToBaseRate()
    {
    }

    /**
     * Test attribute "store_to_quote_rate"
     */
    public function testPropertyStoreToQuoteRate()
    {
    }

    /**
     * Test attribute "base_to_global_rate"
     */
    public function testPropertyBaseToGlobalRate()
    {
    }

    /**
     * Test attribute "base_to_quote_rate"
     */
    public function testPropertyBaseToQuoteRate()
    {
    }

    /**
     * Test attribute "extension_attributes"
     */
    public function testPropertyExtensionAttributes()
    {
    }
}
